#!/bin/sh

# turn off special handling of ._* files in tar, etc.
COPYFILE_DISABLE=1; export COPYFILE_DISABLE

cd /Applications/MAMP/htdocs/billingtracker

cp -pr * /Users/timothyyee/git_repositories/BillingTracker

cd /Users/timothyyee/git_repositories

tar --exclude '.git' --exclude '.DS_Store' -czvf billingtracker.tar.gz BillingTracker

# make sure CodeReuse_tar is existing folder
cp billingtracker.tar.gz BillingTracker_tar

cd BillingTracker/makefile

sftp -P 49430 root@bms.closedarea.com < build_sftp.bat
ssh -T root@bms.closedarea.com -p 49430 < build_ssh.bat